# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee69df00d602137d1245057c8390c1ead636658688ca55622aecc95e6d123ee53ee3b000195d466fd4b1b1659bd5be7771c6fceefd7e5c986a55e84a708c218f

test:
  secret_key_base: eeb03d7a2085020cfefae1d767e6567359b57c2af4ffe4f4c22a27d55271fbd87cc320302a77d0397f935ca2138733e41fcffc28fef180e7b85c96f83364ffc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
